const ALL_ANIMALS = [
    { id: 'hond', name: 'Hond', icon: '🐶', facts: ["Een hondenneus is net zo uniek als een menselijke vingerafdruk!", "Honden kunnen wel tienduizend keer beter ruiken dan wij!", "Honden zweten alleen onder hun voetzooltjes!"] },
    { id: 'kat', name: 'Kat', icon: '🐱', facts: ["Katten slapen soms wel zestien uur per dag!", "Katten kunnen wel honderd verschillende geluiden maken!", "Een kat landt dankzij zijn super flexibele rug bijna altijd op zijn pootjes!"] },
    { id: 'koe', name: 'Koe', icon: '🐮', facts: ["Koeien hebben maar liefst vier magen om gras te verteren!", "Een koe herkauwt haar eten wel vijftig keer per minuut!", "Koeien kunnen de kleur rood helemaal niet zien!"] },
    { id: 'varken', name: 'Varken', icon: '🐷', facts: ["Varkens zijn super slim, soms nog slimmer dan honden!", "Varkens kunnen niet recht naar boven kijken zonder hun hoofd op te tillen!", "Een varken rolt in de modder als een soort zonnebrandcrème!"] },
    { id: 'schaap', name: 'Schaap', icon: '🐑', facts: ["Schapen hebben rechthoekige pupillen waardoor ze bijna achter zich kunnen kijken!", "Wol van één schaap is genoeg voor wel tien truien!", "Schapen kunnen gezichten van andere schapen en mensen onthouden!"] },
    { id: 'paard', name: 'Paard', icon: '🐴', facts: ["Paarden kunnen staand slapen zonder om te vallen!", "De ogen van een paard zijn de grootste van alle landzoogdieren!", "Een veulen kan vlak na de geboorte direct al rennen!"] },
    { id: 'kip', name: 'Kip', icon: '🐔', facts: ["Er zijn veel meer kippen op aarde dan mensen!", "Kippen stammen eigenlijk af van de machtige T-Rex dinosaurus! Bizar he?!", "Kippen kletsen al met hun kuikens als ze nog in het ei zitten!"] },
    { id: 'eend', name: 'Eend', icon: '🦆', facts: ["De veren van een eend zijn zo waterdicht dat hun huid nooit nat wordt!", "Eenden hebben geen zenuwen in hun voeten, dus ze voelen geen kou in de winter!", "Wilde eenden kunnen wel met tachtig kilometer per uur vliegen!"] },
    { id: 'konijn', name: 'Konijn', icon: '🐰', facts: ["De tanden van een konijn stoppen nooit met groeien!", "Konijnen kunnen hun oren 180 graden draaien om heel goed te luisteren!", "Als een konijn heel blij is, maakt hij een gek sprongetje met een draai erin!"] },
    { id: 'muis', name: 'Muis', icon: '🐭', facts: ["Muizen gebruiken hun snorharen om de temperatuur en de wind te voelen!", "De tanden van een muis groeien zo snel dat ze altijd moeten knagen!", "Een muis kan door een gaatje kruipen dat zo smal is als een potlood!"] },
    { id: 'olifant', name: 'Olifant', icon: '🐘', facts: ["Een olifant gebruikt zijn slurf als een ingebouwde snorkel tijdens het zwemmen!", "Olifanten kunnen elkaars voetstappen kilometers verderop voelen trillen!", "De slurf van een olifant heeft wel veertigduizend spieren!"] },
    { id: 'leeuw', name: 'Leeuw', icon: '🦁', facts: ["Het gebrul van een leeuw kun je wel acht kilometer verderop horen!", "Leeuwinnen doen bijna al het jachtwerk, niet de mannetjes met hun grote manen!", "Een leeuw slaapt tot wel twintig uur per dag om energie te sparen!"] },
    { id: 'aap', name: 'Aap', icon: '🐒', facts: ["Sommige apen gebruiken stenen als gereedschap om nootjes te kraken!", "Net als wij mensen, hebben apen unieke vingerafdrukken!", "Brulapen maken zoveel lawaai dat het klinkt als een drilboor in de jungle!"] },
    { id: 'beer', name: 'Beer', icon: '🐻', facts: ["IJsberen hebben eigenlijk een gitzwarte huid onder hun witte vacht!", "Grizzlyberen kunnen net zo hard rennen als een paard in galop!", "Een beer kan een prooi al ruiken van dertig kilometer afstand!"] },
    { id: 'krokodil', name: 'Krokodil', icon: '🐊', facts: ["Krokodillen kunnen niet zweten, ze houden hun bek wagenwijd open om af te koelen!", "Een krokodil slikt stenen in om dieper en makkelijker te kunnen duiken!", "Krokodillen huilen echte tranen als ze eten, dat noemen we krokodillentranen!"] },
    { id: 'slang', name: 'Slang', icon: '🐍', facts: ["Slangen ruiken met hun tong! Super handig in het pikkedonker!", "Sommige slangen kunnen wel twee jaar overleven zonder te eten!", "Slangen hebben geen oogleden en slapen dus met hun ogen open!"] },
    { id: 'tijger', name: 'Tijger', icon: '🐯', facts: ["Elke tijger heeft een uniek streeppatroon, net als een menselijke barcode!", "Tijgers zijn een van de weinige katachtigen die heel erg van zwemmen houden!", "De strepen van een tijger zitten niet alleen in de vacht, maar ook echt op hun huid!"] },
    { id: 'zebra', name: 'Zebra', icon: '🦓', facts: ["Als zebra's dicht bij elkaar staan, raken roofdieren helemaal in de war van al die strepen!", "Zebra's praten met elkaar door hun oren plat te leggen of rechtop te zetten!", "Een veulen herkent zijn moeder feilloos aan haar unieke strepenpatroon!"] },
    { id: 'giraf', name: 'Giraf', icon: '🦒', facts: ["Een giraf heeft net als wij maar zeven nekwervels, ze zijn alleen reusachtig groot!", "De tong van een giraf is paars-blauw zodat hij niet verbrandt in de hete zon!", "Het hart van een giraf weegt wel elf kilo en pompt razend hard bloed naar de nek!"] },
    { id: 'pinguin', name: 'Pinguïn', icon: '🐧', facts: ["Pinguïns gebruiken hun vleugels niet om te vliegen, maar als keiharde zwemvliezen!", "Keizerspinguïns houden hun eieren warm door ze op hun voeten te balanceren!", "Pinguïns kunnen wel vijfhonderd meter diep duiken op jacht naar lekkere vis!"] },
    
    // Extra Dieren (totaal 60)
    { id: 'kikker', name: 'Kikker', icon: '🐸', facts: ["Kikkers drinken geen water met hun mond, ze zuigen het op door hun huid!", "Sommige kikkers bevriezen in de winter en ontdooien in de lente weer om weg te springen!", "Kikkers gebruiken hun ogen om hun eten door te slikken, door ze hard in hun kop te drukken!"] },
    { id: 'schildpad', name: 'Schildpad', icon: '🐢', facts: ["Schildpadden voelen het echt als je ze aait over hun schild, er zitten namelijk zenuwen in!", "Sommige schildpadden kunnen veel ouder dan honderd jaar worden!", "Een schildpad kan zijn schild nooit afdoen, het zit vast aan zijn ruggengraat!"] },
    { id: 'walvis', name: 'Walvis', icon: '🐳', facts: ["De blauwe walvis is het allergrootste dier dat ooit op aarde heeft geleefd!", "Walvissen zingen liedjes voor elkaar die duizenden kilometers ver door de oceaan reizen!", "Het hart van een blauwe walvis is net zo groot als een kleine auto!"] },
    { id: 'dolfijn', name: 'Dolfijn', icon: '🐬', facts: ["Dolfijnen slapen met één oog open om altijd op te blijven letten voor gevaar!", "Ze geven elkaar een soort eigen naam door speciale fluitgeluidjes te maken!", "Dolfijnen gebruiken klik-geluidjes om in het pikdonker vissen te vinden, dat heet echolocatie!"] },
    { id: 'octopus', name: 'Octopus', icon: '🐙', facts: ["Een octopus heeft niet één, maar wel drie harten in zijn lijf!", "Het bloed van een octopus is niet rood, maar donkerblauw!", "Een octopus is zo bizar slim dat hij dichte potjes kan openmaken met zijn tentakels!"] },
    { id: 'krab', name: 'Krab', icon: '🦀', facts: ["De tanden van een krab zitten niet in zijn mond, maar in zijn maag!", "Krabben lopen en zwemmen bijna altijd zijwaarts in plaats van vooruit!", "Als een krab zijn schaar verliest bij een gevecht, groeit er vanzelf weer een hele nieuwe aan!"] },
    { id: 'slak', name: 'Slak', icon: '🐌', facts: ["Een slak kan wel drie jaar lang slapen als het te droog is buiten!", "Slakken hebben duizenden piepkleine tandjes op hun tong zitten!", "Een tuinslak is zo sterk dat hij zonder zich te snijden over de rand van een scherp mes kan kruipen!"] },
    { id: 'rups', name: 'Rups', icon: '🐛', facts: ["Een rups heeft maar één grote taak: zo veel mogelijk blaadjes eten om super snel te groeien!", "Rupsen hebben nul botten, maar wel duizenden kleine spiertjes in hun lijfje!", "Tijdens de verandering in een vlinder, smelt de rups in zijn cocon helemaal tot een soort soepje!"] },
    { id: 'mier', name: 'Mier', icon: '🐜', facts: ["Mieren kunnen dingen dragen die wel vijftig keer zwaarder zijn dan zijzelf!", "Mieren slapen nooit echt diep, ze doen alleen maar hazenslaapjes van een minuut!", "Er leven biljoenen mieren op aarde, ze wegen samen bijna net zoveel als alle mensen op de wereld!"] },
    { id: 'bij', name: 'Bij', icon: '🐝', facts: ["Honingbijen praten met elkaar door een speciaal trillend dansje te doen in de lucht!", "Een bij moet wel twee miljoen bloemen bezoeken voor het maken van één potje honing!", "Bijen kunnen daadwerkelijk de gezichten van mensen onthouden en herkennen!"] },
    { id: 'lieveheersbeestje', name: 'Lieveheersbeestje', icon: '🐞' },
    { id: 'spin', name: 'Spin', icon: '🕷️' },
    { id: 'vleermuis', name: 'Vleermuis', icon: '🦇' },
    { id: 'uil', name: 'Uil', icon: '🦉' },
    { id: 'arend', name: 'Arend', icon: '🦅' },
    { id: 'flamingo', name: 'Flamingo', icon: '🦩' },
    { id: 'pauw', name: 'Pauw', icon: '🦚' },
    { id: 'papegaai', name: 'Papegaai', icon: '🦜' },
    { id: 'zwaan', name: 'Zwaan', icon: '🦢' },
    { id: 'vos', name: 'Vos', icon: '🦊' },
    { id: 'wolf', name: 'Wolf', icon: '🐺' },
    { id: 'everzwijn', name: 'Everzwijn', icon: '🐗' },
    { id: 'nijlpaard', name: 'Nijlpaard', icon: '🦛' },
    { id: 'neushoorn', name: 'Neushoorn', icon: '🦏' },
    { id: 'kameel', name: 'Kameel', icon: '🐪' },
    { id: 'lama', name: 'Lama', icon: '🦙' },
    { id: 'kangoeroe', name: 'Kangoeroe', icon: '🦘' },
    { id: 'luiaard', name: 'Luiaard', icon: '🦥' },
    { id: 'stinkdier', name: 'Stinkdier', icon: '🦨' },
    { id: 'das', name: 'Das', icon: '🦡' },
    { id: 'otter', name: 'Otter', icon: '🦦' },
    { id: 'bever', name: 'Bever', icon: '🦫' },
    { id: 'zeehond', name: 'Zeehond', icon: '🦭' },
    { id: 'hamster', name: 'Hamster', icon: '🐹' },
    { id: 'eekhoorn', name: 'Eekhoorn', icon: '🐿️' },
    { id: 'egel', name: 'Egel', icon: '🦔' },
    { id: 'gorilla', name: 'Gorilla', icon: '🦍' },
    { id: 'orang_oetan', name: 'Orang-oetan', icon: '🦧' },
    { id: 'koala', name: 'Koala', icon: '🐨' },
    { id: 'luipaard', name: 'Luipaard', icon: '🐆' }
];